import * as THREE from 'three'

/**
 * The gallery shell — one continuous swept surface that replaces the five
 * flat wall planes and their hard 90-degree corners with a curved
 * enclosure rising into a vault.
 *
 * **Why one geometry rather than curved wall pieces.** The boxiness the
 * shell had was not only that the walls were flat; it was that they met
 * at corners and stopped dead at the top, so the room read as five
 * rectangles rather than a space. A single parametric surface has no
 * corners to hide and no open top — the plan curve, the springing and the
 * vault are the same sheet of geometry, which is what makes the room feel
 * enclosed by architecture instead of contained by a box.
 *
 * **The plan is a superellipse**, not a circle or a rectangle:
 * `|x/A|^n + |z/B|^n = 1`. At `n = 2` that is an ellipse (fully round, the
 * hall would read as a tube); as `n` rises it approaches a rectangle. The
 * exponent below keeps the long sides reading as walls while every corner
 * rolls through a continuous curve — the hall's approved 20 x 38 footprint
 * is preserved exactly (A and B are its half-extents), so everything
 * derived from those dimensions stays valid.
 *
 * **Two openings are cut from the sheet**, both by skipping cells in the
 * parametric grid rather than by boolean geometry:
 *
 * - The **front mouth**, so the Campaigns pull-back can leave the room.
 *   The camera exits at a bearing of 11.1 degrees from +Z (measured off
 *   the real path, not assumed); `OPENING_HALF_ANGLE` is set far wider so
 *   the frame never catches the opening's edge on the way out. It is an
 *   arch rather than a full-height gap — see `MOUTH_HEIGHT`.
 * A third opening, the **breach**, used to be cut from the +X wall — the
 * fractured hole the old artificial key light streamed through. That lighting
 * concept is gone, and with it the reason for the hole; the sun now enters
 * through the roof, which is the only opening that explains it. The breach is
 * not patched over, it is simply no longer cut: the sweep runs continuously
 * through that arc, carrying the same plan curve, the same `wallWobble`
 * deviation and the same UV parameterisation as the wall either side of it.
 * There is no seam to hide because there is no join — the stone there is the
 * same surface, generated by the same expression, as the stone around it.
 */

// The approved hall footprint — half-extents. Unchanged, deliberately:
// the light's position, the breach, the monitor anchor and every camera
// keyframe are derived from these, so the shell curves *within* the
// existing envelope rather than moving it.
const A = 10
const B = 19

// Plan exponent. 2 = ellipse, large = rectangle. 3.2 keeps the long side
// walls reading as walls (a gallery, not a rotunda) while rolling every
// corner into a continuous sweep.
const PLAN_EXPONENT = 3.2

// Where the wall stops rising vertically and starts turning into vault.
//
// 8.6 / 12.4 -> 5.6 / 8.0. The old springing was not chosen for the room, it
// was chosen for the BREACH: it had to clear that opening's top edge at
// 6.3 + 1.85 = 8.15, because a fractured hole climbing into the curve of a
// vault reads as damage to the roof rather than as a window. With the breach
// closed (see the cell loop below) that constraint is gone, and what it was
// holding up was a roof 12.4 above a camera that never rises past 1.80 — so
// far overhead that it left the frame entirely, the columns ran off the top
// of the viewport as though they continued forever, and the room read as
// unroofed. Nothing signalled that the light came through a hole in a
// ceiling, because no ceiling was ever in shot.
//
// Both drop by the same 0.65, so the vault keeps its proportion to the wall
// it springs from (2.4 / 5.6 against the old 3.8 / 8.6) — this lowers the
// architecture, it does not reshape it. `HALL_HEIGHT` in `Environment.jsx`
// moves by the same factor so the columns still terminate into the springing
// exactly as they did.
const SPRINGING_HEIGHT = 5.6
const CROWN_HEIGHT = 8.0

// The vault tucks in hard across the hall's width and only gently along
// its length, which is what makes it read as a barrel running the length
// of the gallery rather than a dome sat on top of it.
const VAULT_Z_TUCK = 0.35

// The crown keeps a narrow flat ridge instead of tapering to nothing.
// Letting the width scale reach exactly 0 collapses both sides of the
// vault onto the same line, which produces a seam of degenerate,
// zero-area triangles along the ridge — and a seam is a hole: a ray cast
// straight up from the floor at x = 0 passes through it. Verified, not
// assumed; a roof-closure test found exactly that column of interior
// points uncovered and nothing else. A real barrel vault has a ridge
// anyway, so this is the correct form as well as the robust one.
const VAULT_RIDGE_SCALE = 0.05

// Half-width of the front mouth, in degrees off +Z. The camera leaves at
// 11.1 degrees; this is set well past that so no edge enters frame.
const OPENING_HALF_ANGLE = THREE.MathUtils.degToRad(42)

// The mouth is an ARCH, not a full-height gap, and that is structural
// rather than decorative. Cutting it full height would carry the opening
// up through the vault and leave a hole in the roof directly above it —
// which is the same defect `campaigns/RoomCeiling.jsx` existed to patch:
// during the Campaigns pull-back the camera retreats until the room's
// upper boundary rises into frame, and an open roof there stops the room
// reading as an interior. Closing the shell above this height means the
// vault is continuous all the way round, so that component is no longer
// needed at all and has been removed.
//
// 7.0 -> 4.5, following the springing down by the same factor: the mouth is
// cut where `yMid < MOUTH_HEIGHT`, so leaving it at 7.0 under a 5.6 springing
// would have carried the opening up out of the wall and into the vault. Still
// clears the camera by a wide margin — the path never rises above 1.80
// anywhere (measured against the real `sampleCameraPath`, not assumed), so
// the arch is far outside the frustum on the way through.
const MOUTH_HEIGHT = 4.5

// How far the opening tapers in as it approaches the arch's crown. Without
// this the mouth would be a rectangle with a lid; easing the half-angle
// down over the top third turns it into a genuine arched opening.
const MOUTH_SHOULDER = 0.66

/**
 * The roof opening — the court this room is lit through.
 *
 * Modelled on the peristyle atria of the Paphos rock-cut tombs: a
 * rectangular hole cut straight through a thick stone roof, its edge sitting
 * over the colonnade, with substantial roof left on every side so the space
 * still reads as an interior with a bright court in the middle of it rather
 * than as a ruin with the lid off.
 *
 * **It is defined as a footprint in plan, not as a range of the vault's own
 * parameters.** The two are very different things here. A parametric cut
 * would follow the vault's iso-curves and land wherever those happen to go;
 * a plan footprint cuts a genuine rectangle through the roof no matter how
 * the surface above it curves, which is what a hole cut by masons looks like
 * from below. The edge is therefore a curve *on* the vault whose shadow on
 * the floor is a rectangle — the reference's exact geometry.
 *
 * Sized and placed off the pillar ring, not chosen freely:
 * `PILLAR_RING_CENTER` is [0, -4] and `PILLAR_RING_RADIUS` is 5.5, so
 * centring on [0, -4] at 10.0 x 11.0 puts the opening's edge just inside the
 * columns on both axes. The columns then frame the court exactly as the
 * entablature does in the reference, and the daylight lands inside the ring
 * where Film and Digital already stand. Those values are READ from the ring,
 * never the other way round — nothing here moves a pillar.
 */
const ROOF_OPENING = {
  centerX: 0,
  centerZ: -4,
  halfWidth: 5.0,
  halfLength: 5.5,
  // Superellipse, as with the room's own plan: high enough to read as a
  // rectangle, low enough that the corners are radiused rather than mitred.
  exponent: 6,
  /** Depth of the roof slab the opening is cut through. */
  thickness: 0.55,
  /** Width of the flat top surface left either side of the cut. */
  coping: 0.32,
}

/**
 * Edge irregularity — smooth, deterministic, and small.
 *
 * An exact superellipse would read as laser-cut. This is the same restraint
 * as `WALL_DEVIATION`: enough to break the machined line, far too little to
 * be read as a shape of its own.
 */
function roofOpeningEdge(x, z) {
  return 1 + 0.05 * Math.sin(x * 1.7 + z * 0.9) + 0.03 * Math.sin(z * 2.3 - x * 1.1)
}

/** Is this point in plan inside the opening? */
function insideRoofOpening(x, z) {
  const dx = Math.abs(x - ROOF_OPENING.centerX) / ROOF_OPENING.halfWidth
  const dz = Math.abs(z - ROOF_OPENING.centerZ) / ROOF_OPENING.halfLength
  const n = ROOF_OPENING.exponent
  return Math.pow(dx, n) + Math.pow(dz, n) < roofOpeningEdge(x, z)
}

/**
 * The shell's cross-section at height parameter `v`: the height itself, and
 * how far the plan curve is scaled in each axis at that height.
 *
 * Factored out because the roof opening has to ask the same question the
 * vertex loop asks — "where in the world is parameter (theta, v)?" — and the
 * two answers must be the same function, not two copies of it.
 */
function shellSection(v) {
  if (v <= SPLIT) {
    return { y: (v / SPLIT) * SPRINGING_HEIGHT, xScale: 1, zScale: 1 }
  }
  const w = (v - SPLIT) / (1 - SPLIT)
  const arc = Math.sin(w * Math.PI * 0.5)
  const tuck = Math.cos(w * Math.PI * 0.5)
  return {
    y: SPRINGING_HEIGHT + (CROWN_HEIGHT - SPRINGING_HEIGHT) * arc,
    xScale: VAULT_RIDGE_SCALE + (1 - VAULT_RIDGE_SCALE) * tuck,
    zScale: 1 - VAULT_Z_TUCK * (1 - tuck),
  }
}

/** A point on the shell surface at (theta, v), deviation included. */
function shellPoint(theta, v) {
  const section = shellSection(v)
  const p = planPoint(theta)
  const radius = Math.hypot(p.x, p.z) || 1
  const deviation = wallWobble(theta, v) * WALL_DEVIATION
  return {
    x: (p.x + (p.x / radius) * deviation) * section.xScale,
    y: section.y,
    z: (p.z + (p.z / radius) * deviation) * section.zScale,
  }
}

/**
 * Whether the cell centred at (theta, v) falls in the roof opening.
 *
 * The `v > SPLIT` guard is the structural guarantee, not an optimisation:
 * below the springing this surface is vertical WALL, and the opening must
 * never be able to reach it however it is later resized.
 */
function cellInRoofOpening(theta, v) {
  if (v <= SPLIT) return false
  const point = shellPoint(theta, v)
  return insideRoofOpening(point.x, point.z)
}

const RADIAL_SEGMENTS = 260
// 72 -> 108. Purely a sampling change: the swept surface is identical, but the
// roof opening's long edges are curves that cross this grid diagonally, and at
// 72 rows each step in v moved the cut by ~0.14 units, which reads as a
// staircase along an edge that has bright sky behind it.
const HEIGHT_SEGMENTS = 108

/**
 * How far the wall may wander off its ideal sweep, in world units.
 *
 * A superellipse swept perfectly is still a machined surface: every
 * horizontal section is the same curve, so raking light produces an even,
 * mathematically smooth gradient, and the eye reads "extruded shape". Real
 * walls of this age are out of true — they bow, lean and settle by a few
 * centimetres over their height. This is small enough to be invisible as
 * shape and large enough to break that gradient, which is where the
 * machined read actually lives.
 *
 * It is deliberately a low-frequency field, not surface noise: fine
 * roughness is the stone material's job, and doubling it in geometry only
 * produces the busy, sparkly result the brief rules out.
 */
const WALL_DEVIATION = 0.16

/** Deterministic hash, matching `stoneWallMaterial.js`'s approach. */
function hash2D(x, y) {
  const value = Math.sin(x * 12.9898 + y * 78.233) * 43758.5453
  return value - Math.floor(value)
}

/**
 * A smooth field that WRAPS in theta, so the wall closes on itself
 * without a seam where the sweep comes back round.
 */
function wallWobble(theta, v) {
  const turns = 3
  const a = Math.sin(theta * turns + v * 2.1 + 0.7)
  const b = Math.sin(theta * (turns * 2) - v * 1.3 + 2.4) * 0.5
  const c = Math.sin(theta * (turns * 3) + v * 3.7 - 1.1) * 0.25
  // A slow vertical lean on top, so the surface is not merely rippled but
  // genuinely out of plumb in places.
  const lean = Math.sin(theta * 2 + 1.9) * (v - 0.35) * 0.8
  return (a + b + c) * 0.5 + lean
}

// Fraction of the vertical parameter spent below the springing.
const SPLIT = 0.62

/**
 * How far the wall stands off its ideal sweep at (`theta`, `y`), measured
 * along its own plan radius — positive is outward.
 *
 * Exported for the same reason as `planPoint`: anything that has to sit ON
 * this surface has to follow the same wander, or it drifts through it. The
 * wall bows by up to ~0.15 units, which is an order of magnitude more than
 * the clearance a flush inlay can afford — see `wallInscription.js`.
 *
 * Only meaningful below the springing, which is the only part of the shell
 * that is vertical wall rather than vault.
 */
export function wallDeviation(theta, y) {
  return wallWobble(theta, (y / SPRINGING_HEIGHT) * SPLIT) * WALL_DEVIATION
}

/**
 * Superellipse plan radius in the XZ plane, at angle `theta` from +Z.
 *
 * Exported so the floor/wall contact debris can follow the exact same
 * footprint — see `contactDebris.js`. A skirt built on an approximation of
 * this curve would drift away from the wall it is supposed to be joining,
 * which is the one thing it must not do.
 */
export function planPoint(theta) {
  const sin = Math.sin(theta)
  const cos = Math.cos(theta)
  const denom = Math.pow(
    Math.pow(Math.abs(sin) / A, PLAN_EXPONENT) + Math.pow(Math.abs(cos) / B, PLAN_EXPONENT),
    -1 / PLAN_EXPONENT,
  )
  return { x: denom * sin, z: denom * cos }
}

export const GALLERY_SHELL = {
  springingHeight: SPRINGING_HEIGHT,
  crownHeight: CROWN_HEIGHT,
  openingHalfAngle: OPENING_HALF_ANGLE,
  /**
   * The roof opening, in plan. Exported so the lighting can put the sun
   * where the hole actually is instead of carrying its own copy of these
   * numbers — see `ROOF_OPENING` for how they derive from the pillar ring.
   */
  roofOpening: {
    centerX: ROOF_OPENING.centerX,
    centerZ: ROOF_OPENING.centerZ,
    width: ROOF_OPENING.halfWidth * 2,
    length: ROOF_OPENING.halfLength * 2,
    thickness: ROOF_OPENING.thickness,
    /** Height of the roof surface at the middle of the opening. */
    crownHeight: CROWN_HEIGHT,
  },
}

/**
 * Builds the shell. Vertices are laid out on a (theta, v) grid; cells are
 * emitted as triangles only where they are not inside one of the two
 * openings, so the holes are genuine gaps in the surface rather than
 * geometry hidden behind something.
 *
 * Winding is chosen so the surface faces INWARD — the camera lives inside
 * this room, and a shell facing outward would light and shade from the
 * wrong side.
 */
export function buildGalleryShellGeometry() {
  const positions = []
  const uvs = []
  const grid = []

  for (let iy = 0; iy <= HEIGHT_SEGMENTS; iy += 1) {
    const v = iy / HEIGHT_SEGMENTS
    // Vertical wall below the springing, quarter-sine vault above it — see
    // `shellSection`, which the roof opening reads from the same source.
    const { y, xScale, zScale } = shellSection(v)

    const row = []
    for (let ix = 0; ix <= RADIAL_SEGMENTS; ix += 1) {
      const u = ix / RADIAL_SEGMENTS
      const theta = -Math.PI + u * Math.PI * 2
      const p = planPoint(theta)
      // Push the section in or out along its own radius, so the wall bows
      // rather than shearing sideways.
      const radius = Math.hypot(p.x, p.z) || 1
      const deviation = wallWobble(theta, v) * WALL_DEVIATION
      const nx = (p.x / radius) * deviation
      const nz = (p.z / radius) * deviation
      row.push(positions.length / 3)
      positions.push((p.x + nx) * xScale, y, (p.z + nz) * zScale)
      // U follows arc length so the stone's block scale stays even around
      // the sweep; V follows real height for the same reason.
      uvs.push(u, y / CROWN_HEIGHT)
    }
    grid.push(row)
  }

  const indices = []
  for (let iy = 0; iy < HEIGHT_SEGMENTS; iy += 1) {
    for (let ix = 0; ix < RADIAL_SEGMENTS; ix += 1) {
      // Cell centre, used for the opening tests.
      const theta = -Math.PI + ((ix + 0.5) / RADIAL_SEGMENTS) * Math.PI * 2
      const vMid = (iy + 0.5) / HEIGHT_SEGMENTS
      const yMid =
        vMid <= SPLIT
          ? (vMid / SPLIT) * SPRINGING_HEIGHT
          : SPRINGING_HEIGHT +
            (CROWN_HEIGHT - SPRINGING_HEIGHT) * Math.sin(((vMid - SPLIT) / (1 - SPLIT)) * Math.PI * 0.5)

      // Front mouth — an arched opening the camera leaves through. The
      // half-angle holds at full width up to the springing of the arch,
      // then eases to zero at its crown, so the opening closes in a curve
      // rather than stopping against a flat lintel.
      if (yMid < MOUTH_HEIGHT) {
        const shoulder = MOUTH_HEIGHT * MOUTH_SHOULDER
        const taper =
          yMid <= shoulder ? 1 : Math.cos(((yMid - shoulder) / (MOUTH_HEIGHT - shoulder)) * Math.PI * 0.5)
        if (Math.abs(theta) < OPENING_HALF_ANGLE * taper) continue
      }

      // Roof opening — the court. Cut last of the three because it is the
      // only one tested against a plan footprint rather than against the
      // surface's own parameters; see `ROOF_OPENING`.
      if (cellInRoofOpening(theta, vMid)) continue

      const a = grid[iy][ix]
      const b = grid[iy][ix + 1]
      const c = grid[iy + 1][ix + 1]
      const d = grid[iy + 1][ix]
      // Inward-facing winding.
      indices.push(a, d, b, b, d, c)
    }
  }

  // Cap the crown. The swept surface is a tube: closed around theta, but
  // open at both ends. The floor mesh covers the bottom; the top would
  // otherwise be left as a narrow open slot running the length of the
  // ridge — a hole in the roof, found by a straight-up ray test from the
  // floor rather than by looking at it, since from inside the room the
  // slot is edge-on and nearly invisible until the Campaigns pull-back
  // puts the ceiling in frame.
  //
  // The two long sides of that slot are mirror images: the vertex at
  // +theta and the one at -theta share a z and differ only in the sign of
  // x. Stitching each to its mirror closes the slot with a flat ridge
  // band, which is also what a real barrel vault has at its crown.
  const crown = grid[HEIGHT_SEGMENTS]
  const half = RADIAL_SEGMENTS / 2
  for (let ix = 0; ix < half; ix += 1) {
    const left = crown[ix]
    const leftNext = crown[ix + 1]
    const right = crown[RADIAL_SEGMENTS - ix]
    const rightNext = crown[RADIAL_SEGMENTS - ix - 1]
    if (left === right || leftNext === rightNext) continue
    // The ridge band has to be cut wherever the opening reaches the crown,
    // or the hole would be neatly sealed along its own centre line. The band
    // spans x ~ 0 by construction (it stitches +theta to its mirror), so the
    // footprint only has to be asked about z.
    const theta = -Math.PI + ((ix + 0.5) / RADIAL_SEGMENTS) * Math.PI * 2
    if (insideRoofOpening(0, planPoint(theta).z * shellSection(1).zScale)) continue
    // Wound to face down, into the room.
    indices.push(left, right, leftNext, leftNext, right, rightNext)
  }

  const geometry = new THREE.BufferGeometry()
  geometry.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3))
  geometry.setAttribute('uv', new THREE.Float32BufferAttribute(uvs, 2))
  geometry.setIndex(indices)
  geometry.computeVertexNormals()
  geometry.computeBoundingSphere()
  return geometry
}

/**
 * The stone thickness of the roof, exposed around the opening.
 *
 * The shell is a zero-thickness surface, which is invisible everywhere else
 * in this room because every part of it is seen from one side only. A hole
 * is the exception: cut one in a single sheet and from below it reads as
 * torn paper, with the roof having no more substance than a stencil — the
 * opposite of the reference, where the first thing the eye reads is how
 * *deep* the cut through the slab is.
 *
 * So this builds the two faces a real cut exposes:
 *
 *  - the **reveal**, the vertical band running down through the slab, which
 *    is what catches the sun and throws the hard-edged shadow across the
 *    court; and
 *  - the **coping**, the flat top of the roof either side of the cut, which
 *    is why the opening reads as a rim seen from underneath rather than an
 *    edge with nothing behind it.
 *
 * Extruded straight up rather than along the surface normal, deliberately:
 * a roof of bedded stone is cut vertically through horizontal courses, and
 * near the crown — which is where almost all of this edge lives — the
 * surface is close to horizontal anyway, so the two directions agree.
 *
 * Built by walking the same lattice `buildGalleryShellGeometry` walks and
 * asking the same question of it. It does not receive the shell's grid: the
 * cut is a pure function of (theta, v), so re-deriving the boundary here is
 * cheaper than threading state between the two, and it cannot drift out of
 * step with the surface it belongs to.
 */
export function buildRoofOpeningRimGeometry() {
  const positions = []
  const uvs = []
  const indices = []

  const thetaAt = (ix) => -Math.PI + (ix / RADIAL_SEGMENTS) * Math.PI * 2
  const cellOpen = (iy, ix) => {
    if (iy < 0 || iy >= HEIGHT_SEGMENTS) {
      // Above the top row is the crown band, which is cut on the same test.
      if (iy >= HEIGHT_SEGMENTS) {
        const theta = -Math.PI + ((ix + 0.5) / RADIAL_SEGMENTS) * Math.PI * 2
        return insideRoofOpening(0, planPoint(theta).z * shellSection(1).zScale)
      }
      return false
    }
    const wrapped = (ix + RADIAL_SEGMENTS) % RADIAL_SEGMENTS
    return cellInRoofOpening(thetaAt(wrapped + 0.5), (iy + 0.5) / HEIGHT_SEGMENTS)
  }

  /** Outward direction of the opening's edge in plan, from the footprint's own gradient. */
  const outwardAt = (x, z) => {
    const h = 0.05
    const f = (px, pz) => {
      const dx = Math.abs(px - ROOF_OPENING.centerX) / ROOF_OPENING.halfWidth
      const dz = Math.abs(pz - ROOF_OPENING.centerZ) / ROOF_OPENING.halfLength
      return Math.pow(dx, ROOF_OPENING.exponent) + Math.pow(dz, ROOF_OPENING.exponent)
    }
    const gx = f(x + h, z) - f(x - h, z)
    const gz = f(x, z + h) - f(x, z - h)
    const length = Math.hypot(gx, gz) || 1
    return { x: gx / length, z: gz / length }
  }

  /**
   * UVs are world-scale, as everywhere else in this room, so the stone lands
   * at the same block size on the cut face as on the surfaces either side of
   * it. `x + z` is the horizontal run along the edge: the long edges of the
   * opening run in Z (x barely moves) and the short ones in X (z barely
   * moves), so the sum tracks distance along either without needing to know
   * which edge this is.
   */
  const emitBand = (p0, p1, riseFrom, riseTo, spread, flat) => {
    const base = positions.length / 3
    for (const [point, from, to] of [
      [p0, riseFrom, riseTo],
      [p1, riseFrom, riseTo],
    ]) {
      const out = spread ? outwardAt(point.x, point.z) : { x: 0, z: 0 }
      const far = { x: point.x + out.x * spread, z: point.z + out.z * spread }
      positions.push(point.x, point.y + from, point.z)
      positions.push(far.x, point.y + to, far.z)
      if (flat) {
        uvs.push(point.x, point.z, far.x, far.z)
      } else {
        uvs.push(point.x + point.z, point.y + from, far.x + far.z, point.y + to)
      }
    }
    // base+0/1 are the near edge's bottom/top, base+2/3 the far edge's.
    indices.push(base, base + 1, base + 2, base + 1, base + 3, base + 2)
  }

  for (let iy = 0; iy < HEIGHT_SEGMENTS; iy += 1) {
    for (let ix = 0; ix < RADIAL_SEGMENTS; ix += 1) {
      if (!cellOpen(iy, ix)) continue

      const v0 = iy / HEIGHT_SEGMENTS
      const v1 = (iy + 1) / HEIGHT_SEGMENTS
      const t0 = thetaAt(ix)
      const t1 = thetaAt(ix + 1)

      // Each neighbour that is NOT part of the opening means the grid edge
      // between them is a boundary of the hole, and that edge is where the
      // slab's cut face has to appear.
      const edges = []
      if (!cellOpen(iy, ix - 1)) edges.push([shellPoint(t0, v0), shellPoint(t0, v1)])
      if (!cellOpen(iy, ix + 1)) edges.push([shellPoint(t1, v0), shellPoint(t1, v1)])
      if (!cellOpen(iy - 1, ix)) edges.push([shellPoint(t0, v0), shellPoint(t1, v0)])
      if (!cellOpen(iy + 1, ix)) edges.push([shellPoint(t0, v1), shellPoint(t1, v1)])

      for (const [a, b] of edges) {
        // The reveal: straight up through the slab.
        emitBand(a, b, 0, ROOF_OPENING.thickness, 0, false)
        // The coping: the flat roof surface at the top of that cut.
        emitBand(a, b, ROOF_OPENING.thickness, ROOF_OPENING.thickness, ROOF_OPENING.coping, true)
      }
    }
  }

  const geometry = new THREE.BufferGeometry()
  geometry.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3))
  geometry.setAttribute('uv', new THREE.Float32BufferAttribute(uvs, 2))
  geometry.setIndex(indices)
  geometry.computeVertexNormals()
  geometry.computeBoundingSphere()
  return geometry
}
