import * as THREE from 'three'
import { mergeVertices, toCreasedNormals } from 'three/examples/jsm/utils/BufferGeometryUtils.js'

/**
 * The gallery shell — one continuous swept surface that replaces the five
 * flat wall planes and their hard 90-degree corners with a curved
 * enclosure rising into a vault.
 *
 * **Why one geometry rather than curved wall pieces.** The boxiness the
 * shell had was not only that the walls were flat; it was that they met
 * at corners and stopped dead at the top, so the room read as five
 * rectangles rather than a space. A single parametric surface has no
 * corners to hide and no open top — the plan curve, the springing and the
 * vault are the same sheet of geometry, which is what makes the room feel
 * enclosed by architecture instead of contained by a box.
 *
 * **The plan is a superellipse**, not a circle or a rectangle:
 * `|x/A|^n + |z/B|^n = 1`. At `n = 2` that is an ellipse (fully round, the
 * hall would read as a tube); as `n` rises it approaches a rectangle. The
 * exponent below keeps the long sides reading as walls while every corner
 * rolls through a continuous curve — the hall's approved 20 x 38 footprint
 * is preserved exactly (A and B are its half-extents), so everything
 * derived from those dimensions stays valid.
 *
 * **Two openings are cut from the sheet**, both by skipping cells in the
 * parametric grid rather than by boolean geometry:
 *
 * - The **front mouth**, an arch in the front wall. It was first cut for a
 *   camera move that left the room, and is kept as part of the hall's
 *   approved architecture. It is an arch rather than a full-height gap —
 *   see `MOUTH_HEIGHT`.
 * A third opening, the **breach**, used to be cut from the +X wall — the
 * fractured hole the old artificial key light streamed through. That lighting
 * concept is gone, and with it the reason for the hole; the sun now enters
 * through the roof, which is the only opening that explains it. The breach is
 * not patched over, it is simply no longer cut: the sweep runs continuously
 * through that arc, carrying the same plan curve, the same `wallWobble`
 * deviation and the same UV parameterisation as the wall either side of it.
 * There is no seam to hide because there is no join — the stone there is the
 * same surface, generated by the same expression, as the stone around it.
 */

// The approved hall footprint — half-extents. Unchanged, deliberately:
// the light's position, the breach, the monitor anchor and every camera
// keyframe are derived from these, so the shell curves *within* the
// existing envelope rather than moving it.
const A = 10
const B = 19

// Plan exponent. 2 = ellipse, large = rectangle. 3.2 keeps the long side
// walls reading as walls (a gallery, not a rotunda) while rolling every
// corner into a continuous sweep.
const PLAN_EXPONENT = 3.2

// Where the wall stops rising vertically and starts turning into vault.
//
// 8.6 / 12.4 -> 5.6 / 8.0. The old springing was not chosen for the room, it
// was chosen for the BREACH: it had to clear that opening's top edge at
// 6.3 + 1.85 = 8.15, because a fractured hole climbing into the curve of a
// vault reads as damage to the roof rather than as a window. With the breach
// closed (see the cell loop below) that constraint is gone, and what it was
// holding up was a roof 12.4 above a camera that never rises past 1.80 — so
// far overhead that it left the frame entirely, the columns ran off the top
// of the viewport as though they continued forever, and the room read as
// unroofed. Nothing signalled that the light came through a hole in a
// ceiling, because no ceiling was ever in shot.
//
// Both drop by the same 0.65, so the vault keeps its proportion to the wall
// it springs from (2.4 / 5.6 against the old 3.8 / 8.6) — this lowers the
// architecture, it does not reshape it. `HALL_HEIGHT` in `Environment.jsx`
// moves by the same factor so the columns still terminate into the springing
// exactly as they did.
const SPRINGING_HEIGHT = 5.6
const CROWN_HEIGHT = 8.0

// The vault tucks in hard across the hall's width and only gently along
// its length, which is what makes it read as a barrel running the length
// of the gallery rather than a dome sat on top of it.
const VAULT_Z_TUCK = 0.35

// The crown keeps a narrow flat ridge instead of tapering to nothing.
// Letting the width scale reach exactly 0 collapses both sides of the
// vault onto the same line, which produces a seam of degenerate,
// zero-area triangles along the ridge — and a seam is a hole: a ray cast
// straight up from the floor at x = 0 passes through it. Verified, not
// assumed; a roof-closure test found exactly that column of interior
// points uncovered and nothing else. A real barrel vault has a ridge
// anyway, so this is the correct form as well as the robust one.
const VAULT_RIDGE_SCALE = 0.05

// Half-width of the front mouth, in degrees off +Z.
const OPENING_HALF_ANGLE = THREE.MathUtils.degToRad(42)

// The mouth is an ARCH, not a full-height gap, and that is structural
// rather than decorative. Cutting it full height would carry the opening
// up through the vault and leave a hole in the roof directly above it, and
// an open roof stops the room reading as an interior. Closing the shell
// above this height means the vault is continuous all the way round.
//
// 7.0 -> 4.5, following the springing down by the same factor: the mouth is
// cut where `yMid < MOUTH_HEIGHT`, so leaving it at 7.0 under a 5.6 springing
// would have carried the opening up out of the wall and into the vault. Still
// clears the camera by a wide margin — the path never rises above 1.80
// anywhere (measured against the real `sampleCameraPath`, not assumed), so
// the arch is far outside the frustum on the way through.
const MOUTH_HEIGHT = 4.5

// How far the opening tapers in as it approaches the arch's crown. Without
// this the mouth would be a rectangle with a lid; easing the half-angle
// down over the top third turns it into a genuine arched opening.
const MOUTH_SHOULDER = 0.66

/**
 * The roof opening — the court this room is lit through.
 *
 * Modelled on the peristyle atria of the Paphos rock-cut tombs: a
 * rectangular hole cut straight through a thick stone roof, its edge sitting
 * over the colonnade, with substantial roof left on every side so the space
 * still reads as an interior with a bright court in the middle of it rather
 * than as a ruin with the lid off.
 *
 * **It is defined as a footprint in plan, not as a range of the vault's own
 * parameters.** The two are very different things here. A parametric cut
 * would follow the vault's iso-curves and land wherever those happen to go;
 * a plan footprint cuts a genuine rectangle through the roof no matter how
 * the surface above it curves, which is what a hole cut by masons looks like
 * from below. The edge is therefore a curve *on* the vault whose shadow on
 * the floor is a rectangle — the reference's exact geometry.
 *
 * Sized and placed off the pillar ring, not chosen freely:
 * `PILLAR_RING_CENTER` is [0, -4] and `PILLAR_RING_RADIUS` is 5.5, so
 * centring on [0, -4] at 10.0 x 11.0 puts the opening's edge just inside the
 * columns on both axes. The columns then frame the court exactly as the
 * entablature does in the reference, and the daylight lands inside the ring
 * where Film and Digital already stand. Those values are READ from the ring,
 * never the other way round — nothing here moves a pillar.
 */
/**
 * How far the wall continues BELOW the floor plane.
 *
 * The shell's plan curve is bowed by `WALL_DEVIATION`, so its base wanders up
 * to 0.104 units OUTSIDE the floor's own edge — the floor is a flat
 * `HALL_WIDTH` x `HALL_DEPTH` plane, the wall is a wobbled superellipse, and
 * where the wobble pushes outward the two stop short of each other. That
 * hairline was always there and never mattered, because behind it was an
 * unlit void that rendered the same black as the shadowed floor. Putting a
 * bright sky behind the room turned it into a lit crack running along the
 * bottom of the wall.
 *
 * Dropping the bottom row below zero seals it by overlap rather than by
 * fitting two edges together, which is the same reason `contactDebris.js`
 * starts its geometry at `-BURY`: an exact join between a displaced floor and
 * a bowed wall cannot be made watertight, and does not need to be. Nothing
 * about the room changes — the floor is opaque and sits on top, so every
 * millimetre of this is buried. The wall's position, the footprint and the
 * floor are all untouched.
 */
const SHELL_APRON = 0.35

const RADIAL_SEGMENTS = 260
// 72 -> 108. Purely a sampling change: the swept surface is identical, but the
// roof opening's long edges are curves that cross this grid diagonally, and at
// 72 rows each step in v moved the cut by ~0.14 units, which reads as a
// staircase along an edge that has bright sky behind it.
const HEIGHT_SEGMENTS = 108

/**
 * How far the wall may wander off its ideal sweep, in world units.
 *
 * A superellipse swept perfectly is still a machined surface: every
 * horizontal section is the same curve, so raking light produces an even,
 * mathematically smooth gradient, and the eye reads "extruded shape". Real
 * walls of this age are out of true — they bow, lean and settle by a few
 * centimetres over their height. This is small enough to be invisible as
 * shape and large enough to break that gradient, which is where the
 * machined read actually lives.
 *
 * It is deliberately a low-frequency field, not surface noise: fine
 * roughness is the stone material's job, and doubling it in geometry only
 * produces the busy, sparkly result the brief rules out.
 */
const WALL_DEVIATION = 0.16

const ROOF_OPENING = {
  centerX: 0,
  centerZ: -4,
  halfWidth: 5.0,
  halfLength: 5.5,
  /**
   * The CONSTRUCTED shape underneath the damage.
   *
   * This is still a superellipse, and deliberately: the hole is in a built
   * roof, so straight runs of surviving edge are correct and are what keep it
   * from reading as a cave mouth. The break below is what turns those runs
   * into an opening that collapsed rather than one that was cut.
   */
  exponent: 6,
  /** Nominal slab depth. Varied per-angle by `roofEdgeThickness`. */
  thickness: 0.55,
  /** Nominal width of the flat roof top left beside the break. */
  coping: 0.32,
}

/**
 * Where the ceiling gave way.
 *
 * The first version of this opening was a superellipse with a small smooth
 * wobble on its threshold, and it read exactly as the brief describes — a
 * rectangular skylight with noise on it. Two separate things were wrong, and
 * they needed different fixes:
 *
 *  1. The SILHOUETTE was a rectangle. Noise on a rectangle is still a
 *     rectangle: the eye locks onto the four corners and the long parallel
 *     runs, and no amount of high-frequency detail hides them.
 *  2. The CUT was quantised to the mesh. Cells were kept or dropped whole, so
 *     the boundary staircased along grid lines 0.2-0.4 units across — the
 *     blocky read, and the one that survives any change to the shape.
 *
 * This list fixes the first. Each entry is a real event rather than a
 * frequency: a place where a piece of the ceiling came down, given a position
 * on the perimeter, an angular size and a depth. Positive depth takes stone
 * away (the hole grows there), negative leaves a tongue of surviving slab
 * projecting into the opening. They are placed, not sampled — three big ones
 * of clearly different sizes, so the shape has a coherent story of failure
 * with a few large forms, and the runs between them stay comparatively
 * straight and read as the original built edge.
 *
 * `phi` is measured with `atan2(dx, dz)`: 0 is +Z, +PI/2 is +X. The
 * superellipse's own corners sit near +/-0.74 and +/-2.40, so the three
 * outward breaks are aimed at three of the four corners — which is what
 * removes the 90-degree reads — while the fourth is left comparatively intact
 * and only chipped, because a ruin that has failed identically in four places
 * looks designed.
 */
const ROOF_BREAKS = [
  // The main collapse: takes the +X/+Z corner out entirely.
  { phi: 0.82, width: 0.62, depth: 0.26 },
  // A second, smaller failure at the opposite corner.
  { phi: -2.28, width: 0.46, depth: 0.15 },
  // A shallow scallop off the third corner.
  { phi: 2.52, width: 0.34, depth: 0.09 },
  // Surviving slab still projecting into the hole, mid-run.
  { phi: 1.52, width: 0.26, depth: -0.10 },
  { phi: -0.30, width: 0.20, depth: -0.06 },
  // A chip where the fourth corner is otherwise intact.
  { phi: -1.70, width: 0.17, depth: 0.07 },
]

/** Shortest signed angular distance, so breaks wrap correctly at +/-PI. */
function angleDelta(a, b) {
  let d = a - b
  while (d > Math.PI) d -= Math.PI * 2
  while (d < -Math.PI) d += Math.PI * 2
  return d
}

/** Deterministic PRNG, matching `contactDebris.js`'s generator. */
function mulberry32(seed) {
  let a = seed >>> 0
  return () => {
    a = (a + 0x6d2b79f5) | 0
    let t = Math.imul(a ^ (a >>> 15), 1 | a)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

/**
 * The broken perimeter, as a ring of control points.
 *
 * The previous version summed three smooth harmonics and a few Gaussians. It
 * was asymmetric and it was not a rectangle, but everything about it was
 * infinitely differentiable, so every edge arrived as a soft curve and the
 * whole opening read as eroded putty rather than fractured stone. Rock does
 * not break that way. It breaks along planes, leaving straight runs that meet
 * at angles.
 *
 * So the outline is now a closed POLYGON interpolated linearly, not a smooth
 * field. Every control point is a corner by construction, and the corners are
 * where the fractures read. Two kinds of run alternate:
 *
 *  - **intact** — a long angular step with the radius barely moving, which is
 *    the original built edge still standing;
 *  - **shattered** — a cluster of short steps with large radius swings, which
 *    is where a piece came away and left chips, recesses and protruding
 *    tongues of slab.
 *
 * The alternation is random but the STEP SIZES are drawn from two very
 * different distributions, and that is what keeps it from reading as noise:
 * evenly spaced perturbation always looks procedural no matter how it is
 * weighted, whereas long quiet runs punctuated by dense damage reads as
 * history. Seeded, so the ruin is the same ruin on every load.
 *
 * Thickness and erosion are carried on the same points rather than computed
 * from separate functions, so the slab gets thinner exactly where the edge is
 * chipped — one event, one place, three consequences.
 */
function buildFracturePerimeter() {
  const rand = mulberry32(0x4d475254)
  const points = []
  let phi = -Math.PI
  let shattered = false

  while (phi < Math.PI) {
    phi += shattered ? 0.05 + rand() * 0.09 : 0.20 + rand() * 0.28
    const radius = shattered
      ? 1 + (rand() - 0.42) * 0.30
      : 1 + (rand() - 0.5) * 0.07
    points.push({
      phi,
      radius,
      // Thinnest where the stone is most broken.
      thickness: shattered ? 0.42 + rand() * 0.55 : 0.85 + rand() * 0.55,
      erosion: shattered ? 0.9 + rand() * 0.9 : 0.35 + rand() * 0.5,
    })
    if (rand() < (shattered ? 0.30 : 0.20)) shattered = !shattered
  }

  // Close the ring: the last point wraps to the first, so the interpolation
  // below never has a discontinuity at +/-PI.
  points.push({ ...points[0], phi: points[0].phi + Math.PI * 2 })
  return points
}

const FRACTURE_PERIMETER = buildFracturePerimeter()

/**
 * Linear interpolation around that ring — linear, deliberately, because the
 * kinks between segments ARE the fractures. Smooth interpolation here would
 * put the rounded edges straight back.
 */
function fractureAt(phi) {
  let a = phi
  const first = FRACTURE_PERIMETER[0].phi
  while (a < first) a += Math.PI * 2
  while (a > first + Math.PI * 2) a -= Math.PI * 2

  for (let i = 0; i < FRACTURE_PERIMETER.length - 1; i += 1) {
    const p0 = FRACTURE_PERIMETER[i]
    const p1 = FRACTURE_PERIMETER[i + 1]
    if (a >= p0.phi && a <= p1.phi) {
      const t = (a - p0.phi) / (p1.phi - p0.phi || 1)
      return {
        radius: p0.radius + (p1.radius - p0.radius) * t,
        thickness: p0.thickness + (p1.thickness - p0.thickness) * t,
        erosion: p0.erosion + (p1.erosion - p0.erosion) * t,
      }
    }
  }
  return FRACTURE_PERIMETER[0]
}

/**
 * The opening's radius at angle `phi`, as a multiple of the built superellipse.
 *
 * The fractured polygon carries the small and medium damage; the placed breaks
 * on top of it carry the few large collapses that give the opening its overall
 * asymmetry. Clamped so no amount of accumulated damage can close the aperture
 * or run it into the haunches — the sunlight composition depends on this hole
 * staying roughly the size it is.
 */
function roofSilhouette(phi) {
  let r = fractureAt(phi).radius
  for (const brk of ROOF_BREAKS) {
    const d = angleDelta(phi, brk.phi) / brk.width
    r += brk.depth * Math.exp(-d * d)
  }
  return THREE.MathUtils.clamp(r, 0.74, 1.32)
}

/**
 * Signed distance-like field: negative inside the opening, positive in stone.
 *
 * Expressed as `superellipse radius - silhouette radius` rather than as the
 * raw superellipse sum, because the raw sum rises as the sixth power and
 * interpolates terribly. The cut below finds the edge by interpolating this
 * field along mesh edges, so it has to be close to linear near zero or the
 * smooth boundary is smooth in the wrong place.
 */
function roofOpeningField(x, z) {
  const dx = x - ROOF_OPENING.centerX
  const dz = z - ROOF_OPENING.centerZ
  const n = ROOF_OPENING.exponent
  const q =
    Math.pow(Math.abs(dx) / ROOF_OPENING.halfWidth, n) +
    Math.pow(Math.abs(dz) / ROOF_OPENING.halfLength, n)
  return Math.pow(q, 1 / n) - roofSilhouette(Math.atan2(dx, dz))
}

/**
 * Depth of the slab at this point on the perimeter.
 *
 * Carried by the fractured ring rather than by a harmonic, so it steps at the
 * fractures instead of undulating between them. A slab of even depth all the
 * way round was one of the strongest "cut, not broken" cues in the previous
 * version.
 */
function roofEdgeThickness(phi) {
  return ROOF_OPENING.thickness * fractureAt(phi).thickness
}

/** Width of the surviving roof top beside the break. */
function roofCopingWidth(phi) {
  return ROOF_OPENING.coping * (0.5 + fractureAt(phi).thickness * 0.8)
}

/**
 * The exposed inner face, from the ceiling's underside (t = 0) to the top of
 * the slab (t = 1) — now read as BEDDING COURSES rather than as one weathered
 * curve.
 *
 * `out` is a radial offset away from the opening's centre, so positive widens
 * the hole at that height. Alternating signs cut the face into ledges and
 * recesses: a stone roof is laid in courses and breaks along them, so the
 * thickness a collapse exposes is layered, not a single smooth belly. Three
 * shallow steps do the whole job — this is the "larger believable rock forms"
 * the brief asks for rather than displacement detail, which the material's own
 * normal map already supplies.
 *
 * `shade` darkens the recessed courses through vertex colour, so the crevices
 * read as crevices even before a light reaches them. Scaled per-angle by
 * `roofEdgeErosion`, which now steps at the fractures.
 */
const REVEAL_PROFILE = [
  { t: 0, out: 0, shade: 0.55 },
  { t: 0.17, out: -0.08, shade: 0.42 },
  { t: 0.33, out: 0.06, shade: 0.85 },
  { t: 0.51, out: -0.04, shade: 0.5 },
  { t: 0.72, out: 0.12, shade: 1 },
  { t: 1, out: 0.03, shade: 0.9 },
]

function roofEdgeErosion(phi) {
  return fractureAt(phi).erosion
}

/**
 * The shell's cross-section at height parameter `v`: the height itself, and
 * how far the plan curve is scaled in each axis at that height.
 *
 * Factored out because the roof opening has to ask the same question the
 * vertex loop asks — "where in the world is parameter (theta, v)?" — and the
 * two answers must be the same function, not two copies of it.
 */
function shellSection(v) {
  if (v <= SPLIT) {
    return { y: (v / SPLIT) * SPRINGING_HEIGHT, xScale: 1, zScale: 1 }
  }
  const w = (v - SPLIT) / (1 - SPLIT)
  const arc = Math.sin(w * Math.PI * 0.5)
  const tuck = Math.cos(w * Math.PI * 0.5)
  return {
    y: SPRINGING_HEIGHT + (CROWN_HEIGHT - SPRINGING_HEIGHT) * arc,
    xScale: VAULT_RIDGE_SCALE + (1 - VAULT_RIDGE_SCALE) * tuck,
    zScale: 1 - VAULT_Z_TUCK * (1 - tuck),
  }
}

/** A point on the shell surface at (theta, v), deviation included. */
function shellPoint(theta, v) {
  const section = shellSection(v)
  const p = planPoint(theta)
  const radius = Math.hypot(p.x, p.z) || 1
  const deviation = wallWobble(theta, v) * WALL_DEVIATION
  return {
    x: (p.x + (p.x / radius) * deviation) * section.xScale,
    y: section.y,
    z: (p.z + (p.z / radius) * deviation) * section.zScale,
  }
}

/**
 * The opening field sampled at every GRID VERTEX of the vault.
 *
 * Sampled per vertex rather than per cell, and that is the whole trick behind
 * the smooth edge: two neighbouring cells that share a mesh edge read the same
 * two values at its ends, so both place the boundary crossing at the identical
 * point along it. The cut is then continuous across the whole opening by
 * construction, with no welding, no seam tolerance and no extra resolution.
 *
 * Rows below the springing are left null: the opening is in the vault, and
 * this is the guarantee that it can never reach the vertical wall.
 */
function sampleRoofField() {
  const field = []
  for (let iy = 0; iy <= HEIGHT_SEGMENTS; iy += 1) {
    const v = iy / HEIGHT_SEGMENTS
    if (v < SPLIT) {
      field.push(null)
      continue
    }
    const row = new Float64Array(RADIAL_SEGMENTS + 1)
    for (let ix = 0; ix <= RADIAL_SEGMENTS; ix += 1) {
      const theta = -Math.PI + (ix / RADIAL_SEGMENTS) * Math.PI * 2
      const point = shellPoint(theta, v)
      row[ix] = roofOpeningField(point.x, point.z)
    }
    field.push(row)
  }
  return field
}

/** Field value at a grid vertex; +1 (solid stone) anywhere the opening cannot reach. */
function fieldAt(field, iy, ix) {
  const row = field[iy]
  return row ? row[ix] : 1
}

/** Deterministic hash, matching `stoneWallMaterial.js`'s approach. */
function hash2D(x, y) {
  const value = Math.sin(x * 12.9898 + y * 78.233) * 43758.5453
  return value - Math.floor(value)
}

/**
 * A smooth field that WRAPS in theta, so the wall closes on itself
 * without a seam where the sweep comes back round.
 */
function wallWobble(theta, v) {
  const turns = 3
  const a = Math.sin(theta * turns + v * 2.1 + 0.7)
  const b = Math.sin(theta * (turns * 2) - v * 1.3 + 2.4) * 0.5
  const c = Math.sin(theta * (turns * 3) + v * 3.7 - 1.1) * 0.25
  // A slow vertical lean on top, so the surface is not merely rippled but
  // genuinely out of plumb in places.
  const lean = Math.sin(theta * 2 + 1.9) * (v - 0.35) * 0.8
  return (a + b + c) * 0.5 + lean
}

// Fraction of the vertical parameter spent below the springing.
const SPLIT = 0.62

/**
 * How far the wall stands off its ideal sweep at (`theta`, `y`), measured
 * along its own plan radius — positive is outward.
 *
 * Exported for the same reason as `planPoint`: anything that has to sit ON
 * this surface has to follow the same wander, or it drifts through it. The
 * wall bows by up to ~0.15 units, which is an order of magnitude more than
 * the clearance a flush inlay can afford — see `wallInscription.js`.
 *
 * Only meaningful below the springing, which is the only part of the shell
 * that is vertical wall rather than vault.
 */
export function wallDeviation(theta, y) {
  return wallWobble(theta, (y / SPRINGING_HEIGHT) * SPLIT) * WALL_DEVIATION
}

/**
 * Superellipse plan radius in the XZ plane, at angle `theta` from +Z.
 *
 * Exported so the floor/wall contact debris can follow the exact same
 * footprint — see `contactDebris.js`. A skirt built on an approximation of
 * this curve would drift away from the wall it is supposed to be joining,
 * which is the one thing it must not do.
 */
export function planPoint(theta) {
  const sin = Math.sin(theta)
  const cos = Math.cos(theta)
  const denom = Math.pow(
    Math.pow(Math.abs(sin) / A, PLAN_EXPONENT) + Math.pow(Math.abs(cos) / B, PLAN_EXPONENT),
    -1 / PLAN_EXPONENT,
  )
  return { x: denom * sin, z: denom * cos }
}

export const GALLERY_SHELL = {
  springingHeight: SPRINGING_HEIGHT,
  crownHeight: CROWN_HEIGHT,
  openingHalfAngle: OPENING_HALF_ANGLE,
  /**
   * The roof opening, in plan. Exported so the lighting can put the sun
   * where the hole actually is instead of carrying its own copy of these
   * numbers — see `ROOF_OPENING` for how they derive from the pillar ring.
   */
  roofOpening: {
    centerX: ROOF_OPENING.centerX,
    centerZ: ROOF_OPENING.centerZ,
    width: ROOF_OPENING.halfWidth * 2,
    length: ROOF_OPENING.halfLength * 2,
    thickness: ROOF_OPENING.thickness,
    /** Height of the roof surface at the middle of the opening. */
    crownHeight: CROWN_HEIGHT,
  },
}

/**
 * Builds the shell. Vertices are laid out on a (theta, v) grid; cells are
 * emitted as triangles only where they are not inside one of the two
 * openings, so the holes are genuine gaps in the surface rather than
 * geometry hidden behind something.
 *
 * Winding is chosen so the surface faces INWARD — the camera lives inside
 * this room, and a shell facing outward would light and shade from the
 * wrong side.
 */
export function buildGalleryShellGeometry() {
  const positions = []
  const uvs = []
  const grid = []

  for (let iy = 0; iy <= HEIGHT_SEGMENTS; iy += 1) {
    const v = iy / HEIGHT_SEGMENTS
    // Vertical wall below the springing, quarter-sine vault above it — see
    // `shellSection`, which the roof opening reads from the same source.
    const { y: sectionY, xScale, zScale } = shellSection(v)
    // The lowest row alone is carried under the floor — see `SHELL_APRON`.
    // Only its own position moves; every row above it is untouched, and the
    // UV follows the new height so the stone simply continues down rather
    // than stretching over the buried band.
    const y = iy === 0 ? -SHELL_APRON : sectionY

    const row = []
    for (let ix = 0; ix <= RADIAL_SEGMENTS; ix += 1) {
      const u = ix / RADIAL_SEGMENTS
      const theta = -Math.PI + u * Math.PI * 2
      const p = planPoint(theta)
      // Push the section in or out along its own radius, so the wall bows
      // rather than shearing sideways.
      const radius = Math.hypot(p.x, p.z) || 1
      const deviation = wallWobble(theta, v) * WALL_DEVIATION
      const nx = (p.x / radius) * deviation
      const nz = (p.z / radius) * deviation
      row.push(positions.length / 3)
      positions.push((p.x + nx) * xScale, y, (p.z + nz) * zScale)
      // U follows arc length so the stone's block scale stays even around
      // the sweep; V follows real height for the same reason.
      uvs.push(u, y / CROWN_HEIGHT)
    }
    grid.push(row)
  }

  const indices = []
  const field = sampleRoofField()

  /**
   * Boundary crossings, cached by the MESH EDGE they sit on rather than by the
   * cell that asked for one. Both cells sharing an edge get the same vertex
   * index back, so the two halves of the cut meet exactly instead of merely
   * nearly — which is what would otherwise show as a hairline crack with sky
   * behind it.
   */
  const crossings = new Map()
  const crossingOn = (ia, ib, key) => {
    const cached = crossings.get(key)
    if (cached !== undefined) return cached
    const fa = fieldAt(field, ia.iy, ia.ix)
    const fb = fieldAt(field, ib.iy, ib.ix)
    const t = THREE.MathUtils.clamp(fa / (fa - fb), 0, 1)
    const a = grid[ia.iy][ia.ix] * 3
    const b = grid[ib.iy][ib.ix] * 3
    const index = positions.length / 3
    positions.push(
      positions[a] + (positions[b] - positions[a]) * t,
      positions[a + 1] + (positions[b + 1] - positions[a + 1]) * t,
      positions[a + 2] + (positions[b + 2] - positions[a + 2]) * t,
    )
    const au = grid[ia.iy][ia.ix] * 2
    const bu = grid[ib.iy][ib.ix] * 2
    uvs.push(uvs[au] + (uvs[bu] - uvs[au]) * t, uvs[au + 1] + (uvs[bu + 1] - uvs[au + 1]) * t)
    crossings.set(key, index)
    return index
  }

  for (let iy = 0; iy < HEIGHT_SEGMENTS; iy += 1) {
    for (let ix = 0; ix < RADIAL_SEGMENTS; ix += 1) {
      // Cell centre, used for the opening tests.
      const theta = -Math.PI + ((ix + 0.5) / RADIAL_SEGMENTS) * Math.PI * 2
      const vMid = (iy + 0.5) / HEIGHT_SEGMENTS
      const yMid =
        vMid <= SPLIT
          ? (vMid / SPLIT) * SPRINGING_HEIGHT
          : SPRINGING_HEIGHT +
            (CROWN_HEIGHT - SPRINGING_HEIGHT) * Math.sin(((vMid - SPLIT) / (1 - SPLIT)) * Math.PI * 0.5)

      // Front mouth — an arched opening the camera leaves through. The
      // half-angle holds at full width up to the springing of the arch,
      // then eases to zero at its crown, so the opening closes in a curve
      // rather than stopping against a flat lintel.
      if (yMid < MOUTH_HEIGHT) {
        const shoulder = MOUTH_HEIGHT * MOUTH_SHOULDER
        const taper =
          yMid <= shoulder ? 1 : Math.cos(((yMid - shoulder) / (MOUTH_HEIGHT - shoulder)) * Math.PI * 0.5)
        if (Math.abs(theta) < OPENING_HALF_ANGLE * taper) continue
      }

      const a = grid[iy][ix]
      const b = grid[iy][ix + 1]
      const c = grid[iy + 1][ix + 1]
      const d = grid[iy + 1][ix]

      /**
       * Roof opening — the court, cut by marching squares rather than by
       * dropping whole cells.
       *
       * The other two openings above discard a cell if its CENTRE is inside
       * them, which is fine for a hole in a wall the camera passes at speed.
       * It was not fine here: this edge is held in frame against bright sky
       * for the whole opening orbit, and quantising it to the mesh staircased
       * it in 0.2-0.4 unit steps — the blocky read the brief calls out. So
       * this one clips each cell to the exact isoline instead, keeping the
       * polygon on the stone side. The corners it keeps are existing grid
       * vertices; only the crossings are new, so the cut costs a handful of
       * vertices around the perimeter rather than any global subdivision.
       */
      const corners = [
        { ix, iy, index: a },
        { ix: ix + 1, iy, index: b },
        { ix: ix + 1, iy: iy + 1, index: c },
        { ix, iy: iy + 1, index: d },
      ]
      const values = corners.map((corner) => fieldAt(field, corner.iy, corner.ix))
      const inside = values.map((value) => value < 0)
      const insideCount = inside.filter(Boolean).length

      if (insideCount === 4) continue

      if (insideCount === 0) {
        // Untouched cell — inward-facing winding, as everywhere else.
        indices.push(a, d, b, b, d, c)
        continue
      }

      // Straddles the edge: Sutherland-Hodgman against `field >= 0`.
      const edgeKeys = [
        `h:${ix}:${iy}`,
        `v:${ix + 1}:${iy}`,
        `h:${ix}:${iy + 1}`,
        `v:${ix}:${iy}`,
      ]
      const polygon = []
      for (let k = 0; k < 4; k += 1) {
        const next = (k + 1) % 4
        if (!inside[k]) polygon.push(corners[k].index)
        if (inside[k] !== inside[next]) {
          polygon.push(crossingOn(corners[k], corners[next], edgeKeys[k]))
        }
      }
      // Fan, wound to match the untouched cells above.
      for (let k = 1; k + 1 < polygon.length; k += 1) {
        indices.push(polygon[0], polygon[k + 1], polygon[k])
      }
    }
  }

  // Cap the crown. The swept surface is a tube: closed around theta, but
  // open at both ends. The floor mesh covers the bottom; the top would
  // otherwise be left as a narrow open slot running the length of the
  // ridge — a hole in the roof, found by a straight-up ray test from the
  // floor rather than by looking at it, since from inside the room the
  // slot is edge-on and nearly invisible.
  //
  // The two long sides of that slot are mirror images: the vertex at
  // +theta and the one at -theta share a z and differ only in the sign of
  // x. Stitching each to its mirror closes the slot with a flat ridge
  // band, which is also what a real barrel vault has at its crown.
  const crown = grid[HEIGHT_SEGMENTS]
  const half = RADIAL_SEGMENTS / 2
  for (let ix = 0; ix < half; ix += 1) {
    const left = crown[ix]
    const leftNext = crown[ix + 1]
    const right = crown[RADIAL_SEGMENTS - ix]
    const rightNext = crown[RADIAL_SEGMENTS - ix - 1]
    if (left === right || leftNext === rightNext) continue
    // The ridge band has to be cut wherever the opening reaches the crown,
    // or the hole would be neatly sealed along its own centre line. The band
    // spans x ~ 0 by construction (it stitches +theta to its mirror), so the
    // footprint only has to be asked about z.
    const theta = -Math.PI + ((ix + 0.5) / RADIAL_SEGMENTS) * Math.PI * 2
    if (roofOpeningField(0, planPoint(theta).z * shellSection(1).zScale) < 0) continue
    // Wound to face down, into the room.
    indices.push(left, right, leftNext, leftNext, right, rightNext)
  }

  const geometry = new THREE.BufferGeometry()
  geometry.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3))
  geometry.setAttribute('uv', new THREE.Float32BufferAttribute(uvs, 2))
  geometry.setIndex(indices)
  geometry.computeVertexNormals()
  geometry.computeBoundingSphere()
  return geometry
}

/**
 * The stone thickness of the roof, exposed around the opening.
 *
 * The shell is a zero-thickness surface, which is invisible everywhere else
 * in this room because every part of it is seen from one side only. A hole
 * is the exception: cut one in a single sheet and from below it reads as
 * torn paper, with the roof having no more substance than a stencil — the
 * opposite of the reference, where the first thing the eye reads is how
 * *deep* the cut through the slab is.
 *
 * So this builds the two faces a real cut exposes:
 *
 *  - the **reveal**, the vertical band running down through the slab, which
 *    is what catches the sun and throws the hard-edged shadow across the
 *    court; and
 *  - the **coping**, the flat top of the roof either side of the cut, which
 *    is why the opening reads as a rim seen from underneath rather than an
 *    edge with nothing behind it.
 *
 * Extruded straight up rather than along the surface normal, deliberately:
 * a roof of bedded stone is cut vertically through horizontal courses, and
 * near the crown — which is where almost all of this edge lives — the
 * surface is close to horizontal anyway, so the two directions agree.
 *
 * Built by walking the same lattice `buildGalleryShellGeometry` walks and
 * asking the same question of it. It does not receive the shell's grid: the
 * cut is a pure function of (theta, v), so re-deriving the boundary here is
 * cheaper than threading state between the two, and it cannot drift out of
 * step with the surface it belongs to.
 */
/**
 * The rim of the hole, as a list of segments lying exactly on the cut.
 *
 * Extracted from the same field on the same lattice the shell cut uses, so
 * every endpoint lands on a shell crossing exactly rather than merely nearly.
 * Exported because the light shaft is built from it too: a beam that is
 * genuinely the shape of the hole can only come from the hole's own geometry,
 * and deriving it twice would let the two drift apart.
 *
 * Returned unordered. Neither consumer needs a walked loop — the rim extrudes
 * each segment into a slab face, the shaft extrudes each into a wall of the
 * light prism, and the union of those is the surface either way.
 */
export function roofOpeningBoundarySegments() {
  const field = sampleRoofField()
  const thetaAt = (ix) => -Math.PI + (ix / RADIAL_SEGMENTS) * Math.PI * 2

  const crossing = (ia, ib) => {
    const fa = fieldAt(field, ia.iy, ia.ix)
    const fb = fieldAt(field, ib.iy, ib.ix)
    const t = THREE.MathUtils.clamp(fa / (fa - fb), 0, 1)
    const pa = shellPoint(thetaAt(ia.ix), ia.iy / HEIGHT_SEGMENTS)
    const pb = shellPoint(thetaAt(ib.ix), ib.iy / HEIGHT_SEGMENTS)
    return {
      x: pa.x + (pb.x - pa.x) * t,
      y: pa.y + (pb.y - pa.y) * t,
      z: pa.z + (pb.z - pa.z) * t,
    }
  }

  const segments = []
  for (let iy = 0; iy < HEIGHT_SEGMENTS; iy += 1) {
    for (let ix = 0; ix < RADIAL_SEGMENTS; ix += 1) {
      const corners = [
        { ix, iy },
        { ix: ix + 1, iy },
        { ix: ix + 1, iy: iy + 1 },
        { ix, iy: iy + 1 },
      ]
      const inside = corners.map((c) => fieldAt(field, c.iy, c.ix) < 0)
      const count = inside.filter(Boolean).length
      if (count === 0 || count === 4) continue

      const hits = []
      for (let k = 0; k < 4; k += 1) {
        const next = (k + 1) % 4
        if (inside[k] !== inside[next]) hits.push(crossing(corners[k], corners[next]))
      }
      // Two crossings is the ordinary case; four is a saddle cell, rare enough
      // at this density that pairing them in the order found is sufficient.
      for (let k = 0; k + 1 < hits.length; k += 2) segments.push([hits[k], hits[k + 1]])
    }
  }
  return segments
}

/** Is this point in plan inside the opening? Used to seed dust inside the shaft. */
export function isInsideRoofOpening(x, z) {
  return roofOpeningField(x, z) < 0
}

/** Plan bounds of the opening, for rejection-sampling inside it. */
export const ROOF_OPENING_BOUNDS = {
  minX: ROOF_OPENING.centerX - ROOF_OPENING.halfWidth * 1.35,
  maxX: ROOF_OPENING.centerX + ROOF_OPENING.halfWidth * 1.35,
  minZ: ROOF_OPENING.centerZ - ROOF_OPENING.halfLength * 1.35,
  maxZ: ROOF_OPENING.centerZ + ROOF_OPENING.halfLength * 1.35,
}

export function buildRoofOpeningRimGeometry() {
  const positions = []
  const uvs = []
  const colors = []
  const indices = []

  const segments = roofOpeningBoundarySegments()

  /** Outward normal of the opening in plan, from the field's own gradient. */
  const outwardAt = (x, z) => {
    const h = 0.05
    const gx = roofOpeningField(x + h, z) - roofOpeningField(x - h, z)
    const gz = roofOpeningField(x, z + h) - roofOpeningField(x, z - h)
    const length = Math.hypot(gx, gz) || 1
    return { x: gx / length, z: gz / length }
  }

  /**
   * One ring of the slab's exposed face per segment: the eroded inner wall
   * from the ceiling's underside up through the stone, then the flat top
   * beside the break.
   *
   * UVs are world-scale, as everywhere else in this room, so the newly exposed
   * stone lands at the same block size as the ceiling it was broken out of.
   * `x + z` is the run along the edge — the opening's long sides run in Z and
   * its ends in X, so the sum tracks distance along either without the ring
   * needing to know which it is on.
   */
  const ringFor = (point) => {
    const phi = Math.atan2(point.x - ROOF_OPENING.centerX, point.z - ROOF_OPENING.centerZ)
    const out = outwardAt(point.x, point.z)
    const thickness = roofEdgeThickness(phi)
    const erosion = roofEdgeErosion(phi)
    const ring = REVEAL_PROFILE.map((step) => {
      const spread = step.out * erosion
      return {
        x: point.x + out.x * spread,
        y: point.y + thickness * step.t,
        z: point.z + out.z * spread,
        shade: step.shade,
        flat: false,
      }
    })
    const top = ring[ring.length - 1]
    const coping = roofCopingWidth(phi)
    ring.push({
      x: top.x + out.x * coping,
      y: top.y,
      z: top.z + out.z * coping,
      // The roof top is the most weathered surface here and catches the sky
      // directly, so it is the one part that is never darkened.
      shade: 1,
      flat: true,
    })
    return ring
  }

  for (const [a, b] of segments) {
    const ringA = ringFor(a)
    const ringB = ringFor(b)
    const base = positions.length / 3
    for (const ring of [ringA, ringB]) {
      for (const point of ring) {
        positions.push(point.x, point.y, point.z)
        uvs.push(point.flat ? point.x : point.x + point.z, point.flat ? point.z : point.y)
        colors.push(point.shade, point.shade, point.shade)
      }
    }
    const n = ringA.length
    for (let k = 0; k + 1 < n; k += 1) {
      const a0 = base + k
      const a1 = base + k + 1
      const b0 = base + n + k
      const b1 = base + n + k + 1
      indices.push(a0, a1, b0, a1, b1, b0)
    }
  }

  const geometry = new THREE.BufferGeometry()
  geometry.setAttribute('position', new THREE.Float32BufferAttribute(positions, 3))
  geometry.setAttribute('uv', new THREE.Float32BufferAttribute(uvs, 2))
  geometry.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3))
  geometry.setIndex(indices)

  /**
   * Welded, then CREASED — and the second step is what this pass added.
   *
   * Each segment builds its own ring, so neighbouring rings arrive as separate
   * vertices at identical positions. Left that way, `computeVertexNormals`
   * gives every quad its own flat normal and the edge shades as a faceted
   * sawtooth. Welding and averaging fixes that, but it fixes it everywhere:
   * the previous version smoothed the fractures along with everything else,
   * which is exactly why the opening read as rounded and manufactured.
   *
   * `toCreasedNormals` splits the difference the way stone actually does.
   * Below the crease angle, normals average and the surface reads worn;
   * above it, they stay hard and the break reads as a break. 48 degrees sits
   * under the angle between the bedding courses in `REVEAL_PROFILE` and over
   * the gentle variation along a run, so the ledges keep their edges while the
   * runs between them stay smooth.
   */
  const welded = mergeVertices(geometry, 1e-4)
  const creased = toCreasedNormals(welded, THREE.MathUtils.degToRad(48))
  creased.computeBoundingSphere()
  return creased
}
