/**
 * Generated by `scripts/build-prop-assets.mjs` — do not edit by hand.
 *
 * Every full-resolution texture that was lifted out of a prop GLB, keyed by the
 * model and by the glTF material name it belongs to, then by the three.js
 * material property `GLTFLoader` assigns it to. `propTextureUpgrades.js`
 * installs these over the 256px maps the GLB ships with.
 */
export const PROP_TEXTURE_MANIFEST = {
  "camera": {
    "Metal": {
      "map": "/models/camera/textures/Metal-map.webp",
      "normalMap": "/models/camera/textures/Metal-normalMap.webp"
    },
    "BlackPlastic": {
      "map": "/models/camera/textures/BlackPlastic-map.webp",
      "normalMap": "/models/camera/textures/BlackPlastic-normalMap.webp"
    },
    "Misc": {
      "map": "/models/camera/textures/Misc-map.webp",
      "normalMap": "/models/camera/textures/Misc-normalMap.webp"
    }
  },
  "monitor": {
    "mat_computer_details": {
      "map": "/models/monitor/textures/mat_computer_details-map.webp",
      "metalnessMap": "/models/monitor/textures/mat_computer_details-metalnessMap.webp",
      "roughnessMap": "/models/monitor/textures/mat_computer_details-metalnessMap.webp",
      "normalMap": "/models/monitor/textures/mat_computer_details-normalMap.webp"
    },
    "mat_big_details": {
      "map": "/models/monitor/textures/mat_big_details-map.webp",
      "metalnessMap": "/models/monitor/textures/mat_big_details-metalnessMap.webp",
      "roughnessMap": "/models/monitor/textures/mat_big_details-metalnessMap.webp",
      "normalMap": "/models/monitor/textures/mat_big_details-normalMap.webp"
    },
    "mat_keyboard": {
      "map": "/models/monitor/textures/mat_keyboard-map.webp",
      "metalnessMap": "/models/monitor/textures/mat_keyboard-metalnessMap.webp",
      "roughnessMap": "/models/monitor/textures/mat_keyboard-metalnessMap.webp",
      "normalMap": "/models/monitor/textures/mat_keyboard-normalMap.webp"
    },
    "mat_lumball": {
      "map": "/models/monitor/textures/mat_lumball-map.webp",
      "metalnessMap": "/models/monitor/textures/mat_lumball-metalnessMap.webp",
      "roughnessMap": "/models/monitor/textures/mat_lumball-metalnessMap.webp",
      "normalMap": "/models/monitor/textures/mat_lumball-normalMap.webp"
    },
    "mat_emis": {
      "map": "/models/monitor/textures/mat_emis-map.webp",
      "metalnessMap": "/models/monitor/textures/mat_emis-metalnessMap.webp",
      "roughnessMap": "/models/monitor/textures/mat_emis-metalnessMap.webp",
      "emissiveMap": "/models/monitor/textures/mat_emis-emissiveMap.webp"
    },
    "glass": {
      "map": "/models/monitor/textures/glass-map.webp",
      "metalnessMap": "/models/monitor/textures/glass-metalnessMap.webp",
      "roughnessMap": "/models/monitor/textures/glass-metalnessMap.webp"
    }
  }
}
